SELECT SUBSTRING(PRODUCT_CODE, 1, 2) as CATEGORY, COUNT(*) as PRODUCTS
FROM PRODUCT
GROUP BY SUBSTRING(PRODUCT_CODE, 1, 2);
# SELECT *, SUBSTRING(PRODUCT_CODE, 1, 2)
# SELECT * FROM PRODUCT GROUP BY SUBSTRING(PRODUCT_CODE, 0, 2);